steps:
  - label: "Checkout and List Files"
    command:
      - "ls -la"
      - "pwd"
      - "echo 'Hello, world!' > myfile.txt"
      - "cat myfile.txt"
  
  
  - label: "store files in artifacts"
    command: 
      - "echo 'test artifatcs' > artifacts.txt"
      - "buildkite-agent artifact upload 'artifacts.txt'"
    artifact_paths: 
       - artifacts.txt

  - label: "Build docker image"
    command: 
      - "cd services; cd BE"
      - "ls -la"
      -  "docker run build -t be-test-image ."
      - "docker images" 
    artifact_paths: 
       - artifacts.txt


    agents:
      queue: "default"
