steps:
  - label: "Checkout and List Files"
    command:
      - "ls -la"
      - "pwd"
      - "echo 'Hello, world!' > myfile.txt"
      - "cat myfile.txt"
  
  
  - label: "store files in artifacts"
    command: 
      - "echo 'test artifatcs' > artifacts.txt"
      - "buildkite-agent artifact upload 'artifacts.txt'"
      - "docker --version"
    artifact_paths: 
       - artifacts.txt

  - label: "Build docker image"
    command: 
      - "cd services/BE"
      - "ls -la"
      -  "docker build -t be-test-image ."
      - "docker images" 


    agents:
      queue: "default"
