# Use an official Node runtime as a parent image
# FROM node:22.1.0
FROM --platform=linux/x86-64 node:22.1.0

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install any needed packages specified in package.json
RUN npm install

# Bundle app source inside Docker image
COPY . .

# Make port 3001 available outside this container
EXPOSE 30002

# Run the server
CMD ["node", "server.js"]